return {
	crownAbilityReq = {
		Heal = 3,
		Shield = 10,
		Bomb = 25,
		Bat = 1e10,
		Wall = 1e10,
	},
	abilityCost = {
		Dash = 300,
		Heal = 800,
		Bomb = 2200,
		Shield = 6000,
	},
	abilityImages = {
		Dash = "rbxassetid://111111871740046",
		Heal = "rbxassetid://78673186983333",
		Bomb = "rbxassetid://87152807012095",
		Shield = "rbxassetid://76878379656817",
		Wall = "rbxassetid://84703732193880",
		Bat = "rbxassetid://70926945211759",
	}
}